config/routes.rb
AndrewIG::Application.routes.draw do

  get "facebook/facebook"
  get "facebook/posts"
  get '/' => 'home#index', as: :root
  get '/instagram' => 'instagram#instagram'
  get '/instagram/feed' => 'instagram#feed', as: :feed
  post '/instagram/search' => 'instagram#search', as: :search

  get '/sc1' => 'soundcloud#sc1', as: :sc1
  get '/soundcloud' => 'soundcloud#soundcloud'

  get '/github' => 'github#github'
  get '/github/repos' => 'github#repos', as: :repos

  get '/facebook' => 'facebook#facebook', as: :facebook
  get '/facebook/posts' => 'facebook#posts', as: :posts
  get '/facebook/log_out' => 'facebook#log_out', as: :fb_logout

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController
  def log_out
  	res = HTTParty.delete('https://graph.facebook.com/v2.2/me/permissions?access_token='+ session[:fb_acc_token])
  	# OK so we logged out
  	session[:fb_acc_token] = nil
  	redirect_to root_path
  end

  def posts
  	# Awesome long access token
  	# Note that we can't have HTTParty parse the JSON coming back because
  	# occasionally an out-of-bounds character comes through and screws things up.
		res = HTTParty.get('https://graph.facebook.com/oauth/access_token?client_id=' + ENV["FB_CLIENT_ID"] + '&redirect_uri=http://localhost:3000/facebook/posts&client_secret=' + ENV["FB_CLIENT_SECRET"] +
			"&code=#{params["code"]}", {headers: {"Accept" => "application/json"}})
		idx = res.parsed_response.index("access_token=")
		# 13 is the length of "access_token:"
		acc_token = res.parsed_response[idx + 13 .. -1]
		# Trim off the "&expires=518400" crap at the end
		# (essentially it's good for 60 days)
		idx = acc_token.index("&")
		session[:fb_acc_token] = acc_token[0..idx - 1]

		# Now with this access token you can verify it if you need:
		# res = HTTParty.get('https://graph.facebook.com/debug_token?access_token='+ session[:fb_acc_token] +'&input_token=' + session[:fb_acc_token])

		# This so far has defaulted to having a scope of only the public profile

		# The "me" stuff refers to the logged-in user
		# https://graph.facebook.com/me/permissions&access_token=
		#res = HTTParty.get('https://graph.facebook.com/v2.2/me/permissions&access_token=' + acc_token)

		# # # Here's simply a user's name and ID
		# res = HTTParty.get('https://graph.facebook.com/v2.2/me?fields=id,name,link,gender,locale,age_range,email&access_token=' + session[:fb_acc_token], {format: :json})
		# # # This brings back something like:
		# # # {"id"=>"10152747337851668", "name"=>"Lorin Thwaits", "link"=>"https://www.facebook.com/app_scoped_user_id/10152747337851668/", "gender"=>"male", "locale"=>"en_US", "age_range"=>{"min"=>21}}
		# user_id = res.parsed_response["id"]
		# user_name = res.parsed_response["name"]
		# raise user_id + " " + user_name

		# # How about seeing who their friends are, or at least how many there are?
		res = HTTParty.get('https://graph.facebook.com/me/friends?access_token=' + session[:fb_acc_token], {format: :json})
		@friend_count = res.parsed_response["summary"]["total_count"]
  end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
	def github
		# Find the access token
		res = HTTParty.post('https://github.com/login/oauth/access_token',
			{body:{client_id: ENV["GH_CLIENT_ID"],
			 client_secret: ENV["GH_CLIENT_SECRET"],
			 code: params[:code]},
			 headers: {"Accept" => "application/json"}})
		redirect_to repos_path(acc_token: res.parsed_response["access_token"])
	end

	def repos
		# Show info about this user
		headers = {"User-Agent" => "Authentication sample",
			"Authorization" => "token #{params[:acc_token]}"}
		url = "https://api.github.com/user"	# ?access_token=#{URI::escape(params[:acc_token])}
		@user_info = HTTParty.get(url, headers: headers)
		puts @user_info.inspect
		# Based on the URLs returned, let's find out about the repos
		@repos = HTTParty.get(@user_info["repos_url"], headers: headers)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController
	before_action :set_ig_acc_code, only: [:feed, :search]

	def instagram
		# Find the access token
		res = HTTParty.post("https://instagram.com/oauth/access_token/",
		 {body:{client_id: ENV["IG_CLIENT_ID"],
		  client_secret: ENV["IG_CLIENT_SECRET"],
		  grant_type:'authorization_code',
		  redirect_uri:'http://localhost:3000/instagram',
		  code: params[:code]}})
		redirect_to feed_path(acc_token: res.parsed_response["access_token"])
	end

	def feed
		# Show a feed of pictures
		if params[:user_id] # For a given user
			@feed = HTTParty.get("https://api.instagram.com/v1/users/" + URI::escape(params[:user_id]) + "/media/recent?access_token=" +
			 @acc_token)
		else	# This user's folks they follow
			@feed = HTTParty.get("https://api.instagram.com/v1/users/self/feed?access_token=" +
			 @acc_token)
		end
	end

	def search
		# Search users
		@url = "https://api.instagram.com/v1/users/search?q=" + URI::escape(params[
			:search][:query]) + "&access_token=" +
		 params[:acc_token]
		@results = HTTParty.get(@url)
	end

private
	def set_ig_acc_code
		@acc_token = params[:acc_token]
	end
end

app/controllers/smugmug_controller.rb
class SmugmugController < ApplicationController
	def index
		@albums = HTTParty.get("http://api.smugmug.com/services/api/json/1.3.0/?method=smugmug.albums.get&APIKey=G74NPxhieE70QY5IV2i9QYeGaoU2EyLe&SessionID=6d9a73c0e94275ae27a1cf6df0fade4b")
	end
end

app/controllers/soundcloud_controller.rb
require 'soundcloud'

class SoundcloudController < ApplicationController
		def sc1
		# Starting the authentication from scratch here...
		session.delete(:sc_access_token)
		# Now that there's no trace left, go get the client and set the sc_access_token
		set_sc_client

#		raise @client.get("/me").inspect

		# redirect user to authorize URL
		# (will come back to http://localhost:3000/soundcloud)
		redirect_to @client.authorize_url()
	end

	def soundcloud
		set_sc_client

		# Find all the playlists
		@playlists = @client.get("/me/playlists")
		if @playlists.count == 0
			# No playlist?  Let's build one for them!
			@playlists = @client.post('/playlists', :playlist => {
			  title: 'My first dorky playlist',
			  sharing: 'public'
			})
			# And get an array of this one back
			@playlists = @client.get("/me/playlists")
		end

		# Find all the favorited tracks
		@favorites = @client.get("/me/favorites")
	end

	# Soundcloud authentication
	def set_sc_client
		if session[:sc_access_token]
			@client = SoundCloud.new(access_token: session[:sc_access_token])
		elsif params[:code]
			# Get the access token -- sample:
			#<SoundCloud::HashResponseWrapper access_token="1-85347-100761451-723189a958a52f" expires_in=21599 refresh_token="e326afe246cb88e66273528034adddf4" scope="*">
			get_client
			res = @client.exchange_token(code: params[:code])
			session[:sc_access_token] = res.access_token
		else
			get_client
		end
	end
	# Get a soundcloud client
	def get_client
		# create client object with app credentials
		@client = Soundcloud.new(:client_id => ENV['SC_CLIENT_ID'],
          :client_secret => ENV['SC_CLIENT_SECRET'],
          :redirect_uri => 'http://localhost:3000/soundcloud')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facebook_helper.rb
module FacebookHelper
end

app/views/facebook/candlestick.html.erb
<script type="text/javascript" src="http://mbostock.github.com/d3/d3.js?1.25.0"></script>
<script type="text/javascript" src="http://mbostock.github.com/d3/d3.time.js?1.25.0"></script>

<div id="chart"></div>

<script type="text/javascript">
  var width = 900;
  var height = 500;
  String.prototype.format = function() {
    var formatted = this;
    for (var i = 0; i < arguments.length; i++) {
      var regexp = new RegExp('\\{'+i+'\\}', 'gi');
      formatted = formatted.replace(regexp, arguments[i]);
		}
		return formatted;
  };

  var dateFormat = d3.time.format("%Y-%m-%d");
  var end = new Date();
  var start = new Date(end.getTime() - 1000 * 60 * 60 * 24 * 60);
  var data = [];

  function min(a, b){ return a < b ? a : b ; }
  function max(a, b){ return a > b ? a : b; }    
  function buildChart(data){
	  var margin = 50;

	  var chart = d3.select("#chart")
		  .append("svg:svg")
		  .attr("class", "chart")
		  .attr("width", width)
		  .attr("height", height);
	  var y = d3.scale.linear()
		  .domain([d3.min(data.map(function(x) {return x["Low"];})), d3.max(data.map(function(x){return x["High"];}))])
		  .range([height-margin, margin]);
	  var x = d3.scale.linear()
		  .domain([d3.min(data.map(function(d){return dateFormat.parse(d.Date).getTime();})),
	  	  d3.max(data.map(function(d){return dateFormat.parse(d.Date).getTime();}))])
		  .range([margin,width-margin]);

    chart.selectAll("line.x")
     .data(x.ticks(10))
     .enter().append("svg:line")
     .attr("class", "x")
     .attr("x1", x)
     .attr("x2", x)
     .attr("y1", margin)
     .attr("y2", height - margin)
     .attr("stroke", "#ccc");

    chart.selectAll("line.y")
     .data(y.ticks(10))
     .enter().append("svg:line")
     .attr("class", "y")
     .attr("x1", margin)
     .attr("x2", width - margin)
     .attr("y1", y)
     .attr("y2", y)
     .attr("stroke", "#ccc");

    chart.selectAll("text.xrule")
     .data(x.ticks(10))
     .enter().append("svg:text")
     .attr("class", "xrule")
     .attr("x", x)
     .attr("y", height - margin)
     .attr("dy", 20)
     .attr("text-anchor", "middle")
     .text(function(d){ var date = new Date(d * 1000);  return (date.getMonth() + 1)+"/"+date.getDate(); });

    chart.selectAll("text.yrule")
      .data(y.ticks(10))
      .enter().append("svg:text")
      .attr("class", "yrule")
      .attr("x", width - margin)
      .attr("y", y)
      .attr("dy", 0)
      .attr("dx", 20)		 
      .attr("text-anchor", "middle")
      .text(String);

		chart.selectAll("rect")
		  .data(data)
		  .enter().append("svg:rect")
		  .attr("x", function(d) { return x(dateFormat.parse(d.Date).getTime()); })
      .attr("y", function(d) {return y(max(d.Open, d.Close));})		  
		  .attr("height", function(d) { return y(min(d.Open, d.Close))-y(max(d.Open, d.Close));})
		  .attr("width", function(d) { return 0.5 * (width - 2*margin)/data.length; })
      .attr("fill",function(d) { return d.Open > d.Close ? "red" : "green" ;});

    chart.selectAll("line.stem")
      .data(data)
      .enter().append("svg:line")
      .attr("class", "stem")
      .attr("x1", function(d) { return x(dateFormat.parse(d.Date).getTime()) + 0.25 * (width - 2 * margin)/ data.length;})
      .attr("x2", function(d) { return x(dateFormat.parse(d.Date).getTime()) + 0.25 * (width - 2 * margin)/ data.length;})		    
      .attr("y1", function(d) { return y(d.High);})
      .attr("y2", function(d) { return y(d.Low); })
      .attr("stroke", function(d){ return d.Open > d.Close ? "red" : "green"; })
  }

	function appendToData(x){
		if(data.length > 0)
	    return;
	  data = x.query.results.quote;
	  for(var i=0;i<data.length;i++){
	    data[i].timestamp = (new Date(data[i].date).getTime() / 1000);
	  }		  
	  data = data.sort(function(x, y){ return dateFormat.parse(x.Date).getTime() - dateFormat.parse(y.Date).getTime(); });			
	  buildChart(data);		  
	}

  function buildQuery(){
    var symbol = window.location.hash;
    if(symbol === "")
       symbol = "AMZN";
    symbol = symbol.replace("#", "");		  
    var base = "select * from yahoo.finance.historicaldata where symbol = \"{0}\" and startDate = \"{1}\" and endDate = \"{2}\"";
    var getDateString = d3.time.format("%Y-%m-%d");
    var query = base.format(symbol, getDateString(start), getDateString(end));
    query = encodeURIComponent(query);
    var url = "http://query.yahooapis.com/v1/public/yql?q={0}&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=appendToData".format(query);
    return url;
  }

  function fetchData(){		  
    url = buildQuery();		  
    scriptElement = document.createElement("SCRIPT");
    scriptElement.type = "text/javascript";
    // i add to the url the call back function
    scriptElement.src = url;
    document.getElementsByTagName("HEAD")[0].appendChild(scriptElement);
  }

  $(document).ready(fetchData);

</script>

app/views/facebook/posts.html.erb
<h2>Friends</h2>
This user has: <%= @friend_count %> friends
<br />
<br />
<%= link_to "Home", root_path %>

app/views/github/repos.html.erb
<h1>Welcome <%= @user_info["login"] %></h1>
<table>
	<tr><td class="topColumn"><%= image_tag @user_info["avatar_url"] %></td>
	<td>You social butterfly -- you've got <%= @user_info["followers"] %> people following you, and in return are following <%= @user_info["following"] %>.  Here's your <%= @user_info["public_repos"] %> repositories:<br />

		<% @repos.each do |r| %>
			<h3><%= link_to r["name"], r["html_url"] %></h3>
			<%= r["description"] %><br />
			<b>Clone this <%= r["language"] %> app:</b>
			<pre>git clone <%= r["clone_url"] %></pre>
		<% end %>

	</td></tr>
</table>

app/views/home/index.html.erb
<a href="https://api.instagram.com/oauth/authorize/?client_id=<%= ENV["IG_CLIENT_ID"] %>&redirect_uri=http://localhost:3000/instagram&response_type=code">Log into Instagram</a>
<br />
<% if session[:fb_acc_token] %>
	<%= link_to "Log out of FB", fb_logout_path %>
<% else %>
	<%= link_to "Log into FB", "https://www.facebook.com/dialog/oauth?client_id=#{ENV["FB_CLIENT_ID"]}&redirect_uri=http://localhost:3000/facebook/posts&" +
		# You can ask for various permissions:
		"scope=public_profile,email,user_friends" %>
<% end %>
<br />

<br />
<%= link_to "Log into SoundCloud", sc1_path %><br />
<br />
Two issues you might notice when trying to log into SoundCloud:<br />
1. If you log in using Facebook and you haven't yet chosen to allow SoundCloud to post on your facebook wall, it will generally end up on a blank screen.  Simply navigate back to our site and try logging in again and things will be fine.<br />
<br />
2. If the message "The token could not be found." is shown on SoundCloud's site, you will need to log off SoundCloud and log on again.  Then it should log in fine.<br />
<br />

<a href="https://github.com/login/oauth/authorize?scope=user:email&client_id=<%= ENV["GH_CLIENT_ID"] %>">Log into Github</a>

app/views/instagram/feed.html.erb
<%= form_for :search, url: search_path(acc_token: @acc_token) do |f| %>
	SOME DAMNED USER:<%= f.text_field :query %>
	<%= f.submit %>
<% end %>

<% if @feed["data"] %>
	<% @feed["data"].each do |post| %>
		<%= link_to post["link"] do %>
			<% if post["caption"] %>
				<%= post["caption"]["text"] %><br />
			<% end %>
			<%= image_tag post["images"]["thumbnail"]["url"] %><% end %>
		<br />
		from
		<% if post["caption"] %>
			<%= post["caption"]["from"]["full_name"] %><br />
		<% end %>
		<%= post["location"].inspect %>
		<hr />
	<% end %>
<% else %>
	NO FEED DATA!
<% end %>

app/views/instagram/search.html.erb
<% @results["data"].each do |user| %>
	<%= link_to feed_path(acc_token: @acc_token, user_id: user["id"]) do %>
		<%= user["username"] %> - <%= user["bio"] %>
	<% end %>
	<hr />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AndrewIG</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/smugmug/index.html.erb
<% @albums.each do |a| %>
	a.id 
	a.Key
	a.Title
	
	@images = HTTParty.get("http://api.smugmug.com/services/api/json/1.3.0/?method=smugmug.images.get&APIKey=G74NPxhieE70QY5IV2i9QYeGaoU2EyLe&AlbumID=", "a.id", "&AlbumKey=", "a.Key")

	<% @images.each do |a, i| %>
		i.id
		i.Key

		@imageURLs = HTTParty.get("http://api.smugmug.com/services/api/json/1.3.0/?method=smugmug.images.getURLs&APIKey=G74NPxhieE70QY5IV2i9QYeGaoU2EyLe&AlbumID=", "a.id", "&AlbumKey=", "a.Key", "&ImageID=", "i.id", &ImageKey=", "i.Key")

	<% @imageURLs.each do |l| %>
<%= image_tag l.OriginalURL %>

app/views/soundcloud/soundcloud.html.erb
<h1>Playlists:</h1>
<ul>
<% @playlists.each do |p| %>
	<li>
	<%= link_to p.permalink_url do %>
		<%= p.title %>, with <%= p.track_count %> tracks
	<% end %>
	</li>
<% end %>
</ul>
<br />
<br />
<h1>Favorites:</h1>
<ul>
<% @favorites.each do |f| %>
	<li>
	<%= link_to f.permalink_url do %>
		<%= f.title %> ... <%= f.id %>
	<% end %>
	</li>
<% end %>
</ul>